version: '3.4'

services:
  php:
    build:
      context: .
    image: custom_php_image
    container_name: php
    volumes:
      - ./:/var/www/
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
      - ./storage/app/public:/var/www/public/storage
    ports: 
      - "80:80"

  db:
    image: postgres:12-alpine
    container_name: db
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "9987:5432"

volumes:
  db-data: {}
